### ISSUE TITLE
Task :react-native-android-auto:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by michalis-ligopsychakis** [Shopify/react-native-android-auto#6]
Hello :)

I am trying to use this package but when I install it and try to run via 'react-native run-android' I am getting this error in the console :

```
> Task :react-native-android-auto:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings
404 actionable tasks: 3 executed, 401 up-to-date
javacTask: source release 1.8 requires target release 1.8

FAILURE: Build failed with an exception.
```

Any help is welcome :)

**Comment by vvusts** [comment]
I have the same problem did you solved it?

**Comment by michalis-ligopsychakis** [comment]
No I didn't, but I found some related sources that explain the problem ...
However I could not implement the suggested solutions on react native project ..

Here are some links :
- https://stackoverflow.com/questions/29888592/errorjava-javactask-source-release-8-requires-target-release-1-8
- https://www.fatalerrors.org/a/error-java-javactask-source-release-8-requires-target-release-1.8.html

**Comment by josh-deprogram** [comment]
I faced a similar issue regarding the versions not matching to 1.8, I solved this in Android Studio by 
`File > Project Structure > Modules > react-native-android-auto`
Then make sure Target Compatibility matches the source at 1.8 (mine was 1.7)

<img width="691" alt="Screen Shot 2021-08-20 at 10 23 08 am" src="https://user-images.githubusercontent.com/1436537/130160349-c232e2cb-c54a-4c8b-91f6-81bcbe702686.png">

**Comment by vvusts** [comment]
It didn't work.
But I tried fork from https://github.com/badiozam/react-native-android-audo
and this one work fine.

**Comment by michalis-ligopsychakis** [comment]
@josh-deprogram changing JavaVersion.Version_1_7 to 1_ 8 fixed the problem but after that there is error with "cannot find symbol: import com.facebook.react.modules.core.Timing" ..

So I changed the "CarService.java" in "node_modules>react-native-android-auto>android>src/main>java/com/shopify/rnandroidauto"  with the one that @vvusts suggested and now it works..

But what about this line that package suggested: 
import { render } from "./src/car/android-auto/module/AndroidAutoReconciler";
(How can that work ..?)

**Comment by michalis-ligopsychakis** [comment]
Ok I see that there are other problems too in the actual package so it's better to use the module that @vvusts suggested 👍  ..

However, it's still not clear to me how to use this package ...

**Comment by michalis-ligopsychakis** [comment]
I closed this issue cause there was a fix too this specific error ...

**Comment by vvusts** [comment]
@michalis-ligopsychakis have you maybe succeeded to make some app maybe simple hello work or something?
I can't figure how to make simple hello world app with this.

**Comment by michalis-ligopsychakis** [comment]
No I didn't.. I am using this link (https://github.com/android/car-samples) which implements Android Auto with Java in order to do this in native code ...
However the module here (https://github.com/badiozam/react-native-android-audo) has the necessary fixes in order for this package to play but it's not on npm and you have to copy paste the code manually in node_modules ...

**Comment by vvusts** [comment]
@MichaelLutaaya just curious did you success to implement it in native code somehow and if yes can you share some guidelines how to do it maybe?

**Comment by jqn** [comment]
These are the changes needed to run the app:
https://github.com/badiozam/react-native-android-audo/commit/68091ae4052f8a403d514e68e3d7112fe4c899f3

They are fairly simple to implement and once they are done use the npm patch-package library to patch react-native-android-auto.
<img width="1667" alt="Screen Shot 2021-10-28 at 2 28 25 PM" src="https://user-images.githubusercontent.com/9710893/139255478-5ab6fe1f-4776-4ba1-8d81-db1a3ca3f016.png">

**Comment by jqn** [comment]
Well, I got it to build but this is as far as I got. I can't get anything to render on the screen hahah! anyone willing to help
<img width="1042" alt="Screen Shot 2021-10-29 at 1 35 17 PM" src="https://user-images.githubusercontent.com/9710893/139427943-03e50b61-955a-41d8-b7f4-1a274523f99a.png">
p?
