### ISSUE TITLE
Example app

### ISSUE THREAD

**Issue by jqn** [Shopify/react-native-android-auto#8]
Hi! I'm wondering if anyone has used this library and successfully build an Android Auto app. I would be great to have an example app since I can't seem to get the emulator to render the Android Auto screen. Could someone direct me to the correct place if I'm doing something wrong or is this library not maintained at all? Best

**Comment by jqn** [comment]
It seems like this project is completely abandoned for now. If you came here looking for a working version of this please look at my repo https://github.com/jqn/AndroidAutoExample it has a working example with the necessary patches to get this thing running. The package.json can't be patched so make sure you update the react-native-android-auto package.json in node modules to this.

```
{
  "name": "react-native-android-auto",
  "title": "React Native Android Auto",
  "version": "1.0.0",
  "description": "Android auto integration for React native apps",
  "main": "index.ts",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "tsc --build",
    "prettier": "prettier -w .",
    "prepublish": "npm run build"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/github_account/react-native-android-auto.git",
    "baseUrl": "https://github.com/github_account/react-native-android-auto"
  },
  "keywords": [
    "react-native"
  ],
  "author": {
    "name": "Your Name",
    "email": "yourname@email.com"
  },
  "license": "private",
  "licenseFilename": "LICENSE",
  "readmeFilename": "README.md",
  "peerDependencies": {
    "react": ">=16.8.6",
    "react-native": ">=0.62.0"
  },
  "devDependencies": {
    "prettier": "^2.1.2"
  },
  "dependencies": {
    "lodash": "^4.17.20",
    "react-reconciler": "^0.26.1"
  }
}
```

Example screenshot

<img width="912" alt="Screen Shot 2021-12-06 at 5 24 34 PM" src="https://user-images.githubusercontent.com/9710893/144883862-3069ac3c-6541-46ac-93da-ae2c8ad78404.png">

**Comment by emmanuelfrancis** [comment]
Hi @jqn I am able to run your project, after coping package.json to "react-native-auto" but DHU does not show the app.

**Comment by AkshayWazir** [comment]
This doesn't work now.
