### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by jqn** [Shopify/react-native-android-auto#9]
Hi, just adding a note here. I spent a lot of time trying to get this to work but so far I'm unsure if this project is a finished project or if it worked at all at some point. I also asked a couple of times for support and there is no answers/help from anyone. It would be great if there was a warning on the README about the status of this project, or at least there is this issue. Thanks.

**Comment by ChrisWiles** [comment]
Abandoned

**Comment by jqn** [comment]
If you are interested in getting this to work, please look at my fork here https://github.com/Reactor-Labs/react-native-android-auto The module is mostly working at this point but it has a bug where the templates won't update, and there are features that need to be built. This is the companion app https://github.com/Reactor-Labs/ReactNativeAndroidAutoExample

**Comment by jqn** [comment]
Closing this
